### PR TITLE
Added Contributing.md File to the bigInt Repo

### PR DESCRIPTION
**Pull request by ashishpetwal**
Just fixed the issue #6 by adding contributing.md file in the main branch of bigInt repo.

### CODE REVIEW

**Comment by ashishpetwal** [comment]
Hey @tanyakr12 I have added the file kindly merge it

**Comment by tanyakr12** [comment]
Looks cool, merging. Thanks for contributing :)

**Comment by tanyakr12** [comment]
By the way, @ashishpetwal kindly name the pull request smaller e.g. this PR could be named as `add: contributing.md` :)
P.S.: No need to change this one

**Comment by tanyakr12** [comment]
closes #8

**Pull request merged**
